steps:
- name: node
  entrypoint: npm
  args: ["install"]
- name: node
  entrypoint: npm
  args: ["test"]
  secretEnv: ["SECRET", "MONGODB_URI"]
  env: ["TEST_PORT=3001"]
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker login --username=$$USERNAME --password=$$PASSWORD"]
  secretEnv: ["USERNAME", "PASSWORD"]
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker build -t $$USERNAME/bloglist-backend-cicd:gcp ."]
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker push $$USERNAME/bloglist-backend-cicd:gcp"]

availableSecrets:
  secretManager:
    - versionName: projects/752307683630/secrets/docker-password/versions/1
      env: "PASSWORD"
    - versionName: projects/752307683630/secrets/docker-username/versions/1
      env: "USERNAME"
    - versionName: projects/752307683630/secrets/mongodb/versions/1
      env: "MONGODB_URI"
    - versionName: projects/752307683630/secrets/secret/versions/1
      env: "SECRET"
